dist: xenial

language: java

services:
  - docker

script:
  - ./gradlew build
  - ./gradlew test
  - ./gradlew run
  - ./gradlew jibBuildTar
  - ./gradlew jibDockerBuild
  - docker run -it --rm myimage

